"""Single entry point that reproduces the entire demonstration.

Usage:
    python scripts/run_demo.py

Pipeline:
    1. Generate the synthetic data from the fixed seed and commit it to data/.
    2. Fit completion and length regressions (naive and adjusted).
    3. Fit the optional half-star rounding RDD.
    4. Write JSON artifacts and a human-readable summary to outputs/.
    5. Render all figures to docs/images/.

Everything is deterministic. Rerunning reproduces identical numbers and figures.
"""
from __future__ import annotations

import os
import sys

sys.path.insert(0, os.path.dirname(os.path.dirname(os.path.abspath(__file__))))

from src import analysis, figures  # noqa: E402
from src.data_generation import build_dataset, save_dataset  # noqa: E402
from src.rdd import build_rdd_frame, estimate_rdd  # noqa: E402
from src.utils import write_json  # noqa: E402


def _recovery_report(cfg, completion, length, rdd_result, raw):
    """Assemble a ground-truth-vs-recovered comparison for integrity checking."""
    cm = cfg["completion_model"]
    lm = cfg["length_model"]
    return {
        "note": (
            "All 'recovered' numbers are from the adjusted specifications that "
            "control for confounders. 'naive' numbers omit controls and are biased."
        ),
        "completion_u_shape_coef": {
            "ground_truth": cm["star_u_coef"],
            "recovered_adjusted": completion["adjusted_quadratic"]["star_u_coef"],
            "recovered_adjusted_ci": completion["adjusted_quadratic"]["star_u_ci"],
            "naive": completion["naive_quadratic"]["star_u_coef"],
            "naive_ci": completion["naive_quadratic"]["star_u_ci"],
        },
        "length_u_shape_coef_log_scale": {
            "ground_truth": lm["star_u_coef"],
            "recovered_negbin": length["negbin_adjusted_quadratic"]["star_u_coef"],
            "recovered_negbin_ci": length["negbin_adjusted_quadratic"]["star_u_ci"],
            "recovered_ols_log": length["ols_adjusted_quadratic"]["star_u_coef"],
            "naive_ols_log": length["ols_naive_quadratic"]["star_u_coef"],
        },
        "rdd_jump": {
            "ground_truth": rdd_result["injected_jump"],
            "recovered": rdd_result["estimated_jump"],
            "recovered_ci": rdd_result["estimated_jump_ci"],
        },
    }


def _fmt_pct(x):
    return "{:.1f}%".format(100.0 * x)


def _write_summary(cfg, raw, completion, length, rdd_result, recovery, fig_paths, save_paths):
    """Write a readable Markdown summary of the run to outputs/summary.md."""
    stars = [1, 2, 3, 4, 5]
    adj_curve = completion["adjusted_categorical"]["star_curve"]
    len_curve = length["ols_adjusted_categorical"]["star_curve_words"]

    lines = []
    lines.append("# Run summary: star rating and the review-creation funnel")
    lines.append("")
    lines.append(
        "Generated by `python scripts/run_demo.py`. All numbers below are from the "
        "actual run on synthetic data with seed {}. This is an observational "
        "analysis on synthetic data: results are associations, not causal effects.".format(
            cfg["seed"]
        )
    )
    lines.append("")

    lines.append("## Data")
    lines.append("")
    n_att = sum(raw[s]["n_attempts"] for s in stars)
    lines.append("- Review attempts: {:,}".format(n_att))
    lines.append("- Businesses: {:,}".format(cfg["n_businesses"]))
    overall_completion = sum(
        raw[s]["completion_rate"] * raw[s]["n_attempts"] for s in stars
    ) / n_att
    lines.append("- Overall completion rate: {}".format(_fmt_pct(overall_completion)))
    lines.append("- Files: `{}`, `{}`".format(
        os.path.relpath(save_paths["attempts"]), os.path.relpath(save_paths["businesses"])
    ))
    lines.append("")

    lines.append("## Completion U-shape by intended star")
    lines.append("")
    lines.append("| Star | Raw completion | Adjusted completion | Share mobile | Mean experience (z) |")
    lines.append("| ---- | -------------- | ------------------- | ------------ | ------------------- |")
    for s in stars:
        lines.append("| {} | {} | {} | {} | {:+.2f} |".format(
            s,
            _fmt_pct(raw[s]["completion_rate"]),
            _fmt_pct(adj_curve[s]),
            _fmt_pct(raw[s]["share_mobile"]),
            raw[s]["mean_experience_z"],
        ))
    lines.append("")
    lines.append(
        "Injected U-shape coefficient on (star-3)^2 was {:.3f}. Recovered "
        "(adjusted): {:.3f} with 95% CI [{:.3f}, {:.3f}]. Naive (no controls): "
        "{:.3f} with 95% CI [{:.3f}, {:.3f}]. Controlling for confounders moves "
        "the estimate toward the truth.".format(
            recovery["completion_u_shape_coef"]["ground_truth"],
            recovery["completion_u_shape_coef"]["recovered_adjusted"],
            recovery["completion_u_shape_coef"]["recovered_adjusted_ci"][0],
            recovery["completion_u_shape_coef"]["recovered_adjusted_ci"][1],
            recovery["completion_u_shape_coef"]["naive"],
            recovery["completion_u_shape_coef"]["naive_ci"][0],
            recovery["completion_u_shape_coef"]["naive_ci"][1],
        )
    )
    lines.append("")

    lines.append("## Length pattern by intended star (completed reviews)")
    lines.append("")
    lines.append("| Star | Raw mean words | Adjusted mean words |")
    lines.append("| ---- | -------------- | ------------------- |")
    for s in stars:
        lines.append("| {} | {:.1f} | {:.1f} |".format(
            s, raw[s]["mean_length"], len_curve[s]
        ))
    lines.append("")
    lines.append(
        "Injected length coefficient on (star-3)^2 (log scale) was {:.3f}. "
        "Recovered by negative binomial GLM: {:.3f} with 95% CI [{:.3f}, {:.3f}]. "
        "OLS-on-log naive: {:.3f}, adjusted: {:.3f}. The negative sign confirms "
        "reviews are shorter at the extremes.".format(
            recovery["length_u_shape_coef_log_scale"]["ground_truth"],
            recovery["length_u_shape_coef_log_scale"]["recovered_negbin"],
            recovery["length_u_shape_coef_log_scale"]["recovered_negbin_ci"][0],
            recovery["length_u_shape_coef_log_scale"]["recovered_negbin_ci"][1],
            recovery["length_u_shape_coef_log_scale"]["naive_ols_log"],
            recovery["length_u_shape_coef_log_scale"]["recovered_ols_log"],
        )
    )
    lines.append("")

    lines.append("## Model fit")
    lines.append("")
    lines.append("- Completion, naive logit pseudo-R2: {:.4f}".format(
        completion["naive"]["pseudo_r2"]))
    lines.append("- Completion, adjusted logit pseudo-R2: {:.4f}".format(
        completion["adjusted_categorical"]["pseudo_r2"]))
    lines.append("- Length, naive OLS R2: {:.4f}".format(length["ols_naive"]["r2"]))
    lines.append("- Length, adjusted OLS R2: {:.4f}".format(
        length["ols_adjusted_categorical"]["r2"]))
    lines.append("")

    lines.append("## Optional RDD: half-star rounding")
    lines.append("")
    lines.append(
        "- Injected jump: {:.3f}, estimated: {:.3f} with 95% CI [{:.3f}, {:.3f}] "
        "(local linear, bandwidth {}, n in band {:,}).".format(
            rdd_result["injected_jump"],
            rdd_result["estimated_jump"],
            rdd_result["estimated_jump_ci"][0],
            rdd_result["estimated_jump_ci"][1],
            rdd_result["bandwidth"],
            rdd_result["n_in_band"],
        )
    )
    lines.append("")

    lines.append("## Figures")
    lines.append("")
    for name, path in fig_paths.items():
        lines.append("- {}: `{}`".format(name, os.path.relpath(path)))
    lines.append("")

    lines.append("## Caveats")
    lines.append("")
    lines.append(
        "- Synthetic data only. The purpose is to demonstrate the analysis type "
        "and communication, not to report real platform metrics."
    )
    lines.append(
        "- Observational design. Star rating is not randomly assigned, so the "
        "recovered relationships are associations after adjusting for observed "
        "confounders. Unobserved confounders could remain."
    )
    lines.append(
        "- A causal estimate would need randomization (for example randomizing a "
        "nudge in the composer) or a credible natural experiment."
    )
    lines.append("")

    path = os.path.join(os.path.dirname(os.path.dirname(os.path.abspath(__file__))),
                        "outputs", "summary.md")
    with open(path, "w", encoding="utf-8") as handle:
        handle.write("\n".join(lines))
    return path


def main() -> None:
    print("[1/5] Generating synthetic data ...")
    cfg, businesses, attempts = build_dataset()
    save_paths = save_dataset(businesses, attempts)

    print("[2/5] Fitting completion and length regressions ...")
    prepared = analysis.prepare(attempts)
    raw = analysis.raw_descriptives(prepared)
    completion = analysis.fit_completion(prepared)
    length = analysis.fit_length(prepared)

    print("[3/5] Fitting half-star rounding RDD ...")
    rdd_frame = build_rdd_frame(cfg, businesses)
    rdd_result = estimate_rdd(cfg, rdd_frame)

    print("[4/5] Writing output artifacts ...")
    recovery = _recovery_report(cfg, completion, length, rdd_result, raw)
    write_json({"by_star": raw}, "raw_by_star.json")
    write_json(completion, "completion_model.json")
    write_json(length, "length_model.json")
    write_json(rdd_result, "rdd.json")
    write_json(recovery, "naive_vs_adjusted.json")

    print("[5/5] Rendering figures ...")
    fig_paths = figures.generate_all(raw, completion, length, rdd_frame, rdd_result)

    summary_path = _write_summary(
        cfg, raw, completion, length, rdd_result, recovery, fig_paths, save_paths
    )

    print("")
    print("Done. Key recovered numbers:")
    print("  completion U-shape coef (truth {:.3f}) -> adjusted {:.3f}, naive {:.3f}".format(
        recovery["completion_u_shape_coef"]["ground_truth"],
        recovery["completion_u_shape_coef"]["recovered_adjusted"],
        recovery["completion_u_shape_coef"]["naive"],
    ))
    print("  length U-shape coef    (truth {:.3f}) -> negbin {:.3f}".format(
        recovery["length_u_shape_coef_log_scale"]["ground_truth"],
        recovery["length_u_shape_coef_log_scale"]["recovered_negbin"],
    ))
    print("  RDD jump               (truth {:.3f}) -> estimated {:.3f}".format(
        recovery["rdd_jump"]["ground_truth"],
        recovery["rdd_jump"]["recovered"],
    ))
    print("  summary: {}".format(os.path.relpath(summary_path)))


if __name__ == "__main__":
    main()
